### ISSUE TITLE
.get(url) with `useWebKit: true` in iOS does not return exact match domain cookie

### ISSUE THREAD

**Issue by williamchong007** [react-native-community/cookies#15]
# Bug
`CookieManager.get('https://google.com', true)` returns cookies of domain with leading dot(e.g. `.google.com`), but not the ones with exact match domain (e.g. `google.com`). This issue only happens in iOS with Webkit option on. Both cookies appear no problem if I call `getAll(true)`.

## Environment info
React native info output:

```bash
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 222.88 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.3, 26.0.0, 26.0.1, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 1.1.0

## Steps To Reproduce

Make sure you use iOS to test:
1. Populate cookie store with cookies having both leading dot and exact match domain, say `google.com` and `.google.com`.
2. Call `CookieManager.getAll(true)`, observe both cookies exists in store
3. Call `CookieManager.get('https://google.com', true)`, only the cookie with leading dot (`.google.com`) is returned, not the one with exact match ('google.com').
...

Describe what you expected to happen:

1. Both cookies should be matched and returned when I call `get(url)`

## Reproducible sample code
```javascript
  // ios sample code
  /* set exact match domain */
  await CookieManager.set({
    name: 'foo',
    value: 'foo',
    domain: 'google.com',
    origin: 'google.com',
    path: '/',
    version: '1',
    expiration: '2021-05-30T12:30:00.00-05:00',
  })
  /* set leading dot domain */
  await CookieManager.set({
    name: 'bar',
    value: 'bar',
    domain: '.google.com',
    origin: 'google.com',
    path: '/',
    version: '1',
    expiration: '2021-05-30T12:30:00.00-05:00',
  })
  console.log(await CookieManager.getAll(true)) // foo, bar both exists
  const test = await CookieManager.get('https://google.com', true)
  console.log(test) // only bar shows up
```

**Comment by safaiyeh** [comment]
Thanks for the issue @williamchong007, I did notice the appending of the `.` last night.

So the ideal would be that `.google.com` and `google.com` to be treated as different hosts when evaluating cookies?

**Comment by safaiyeh** [comment]
Also can you validate the behavior on Android? The behaviors should match.

**Comment by williamchong007** [comment]
We should match browser behaviour if possible. If I query .get() with the url `https://google.com`, both `google.com` and `.google.com` cookie should be returned, since former is an exact match, and the latter one with dot should match all urls with  `*.google.com`, `*.*.google.com` and also `google.com`.

On Android both cookies are return correctly, which is the expected cookie behaviour if I am on a browser.

**Comment by safaiyeh** [comment]
Cool thanks for the clarification. I'll check this out sometime this week.
