### ISSUE TITLE
Android Migration from React Native dependency 

### ISSUE THREAD

**Issue by safaiyeh** [react-native-community/cookies#19]
# Feature Request

Currently the module relies on, [`ForwardingCookieHandler`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/network/ForwardingCookieHandler.java) from `react-native`. This is a proposal to implement cookie APIs from scratch.

## Why it is needed
Since the module relies on the ForwardingCookieHandler, any changes requires a PR to be approved in React Native core. This may cause bug fixes/features to be denied or have longer release cycles.

For example this PR to expose a method: https://github.com/facebook/react-native/pull/27512

When the fix is released (possible cherry picked into v0.62), users of this module must have React Native v0.62. This should be agnostic from the React Native version.

## Possible implementation
We will need to use [Android's WebKit CookieManager](https://developer.android.com/reference/android/webkit/CookieManager) to persist cookies in applications.

[Java's CookieHandler](https://docs.oracle.com/javase/7/docs/api/java/net/CookieHandler.html) will be used to validate & create cookies to follow HTTP policy.

### Code sample

TBD

**Comment by YoliFD** [comment]
This should mostly be resolved now with PR #45. I do however believe we probably have an outstanding issue with setFromResponse especially considering #48

**Comment by safaiyeh** [comment]
Closing as this migration happened with #45
