### ISSUE TITLE
Support CookieManager.set() on Android

### ISSUE THREAD

**Issue by masoudltf** [react-native-community/cookies#25]
# Question

I have got two errors

1-With RN autolinking:
"
Invariant Violation: @react-native-community/cookies: Import libraries to android "react-native link @react-native-community/cookies
"

2-Whit Manual linking and then calling CookieManager.set:
"
Counld not invoke RNCookieManagerAndroid.set

null

Cannot call on android, try setFromResponse
"

Why i'm not able to use this module?

**Comment by safaiyeh** [comment]
Hi @masoudltf I created a fresh React Native project with `npx react-native init CookieTest`, installed the module `yarn add @react-native-community/cookies`, and then 

```javascript
import CookieManager from '@react-native-community/cookies';
CookieManager.get('https://google.com');
```

I did not get the same error as you. Could you provide a reproducible demo?

**Comment by masoudltf** [comment]
Hi @safaiyeh 
I'm trying to move my project to latest RN version and i created a fresh project because i used so many third party modules, well i have to install, config and test every module one by one.
in this case, i used "CookieManager.set()" method and i get these errors.

Thanks very much.

**Comment by safaiyeh** [comment]
Oh yeah, so `set` is not supported on Android. If you checkout https://github.com/react-native-community/cookies#usage, set is iOS only.

It should be implemented on Android as well, so I'll take this issue to support set.

**Comment by masoudltf** [comment]
Thanks bro.

**Comment by David-moonsite** [comment]
> Oh yeah, so `set` is not supported on Android. If you checkout https://github.com/react-native-community/cookies#usage, set is iOS only.
> 
> It should be implemented on Android as well, so I'll take this issue to support set.

Hi , when "set" will be supported on Android ?

**Comment by safaiyeh** [comment]
Hi @David-moonsite  no current plan yet, if you would like to take up the task, I would happily take a PR.

**Comment by SVinay27** [comment]
i am also not able to set cookies for android..
when you provide for android. or any way to set cookies for android

its woks fine for IOS

**Comment by xchwarze** [comment]
Android represents +85% of mobile marketshare.... 
maybe this repo https://github.com/fanduel/cookies can solve this criminal omission

**Comment by safaiyeh** [comment]
> Android represents +85% of mobile marketshare.... 
> 
> maybe this repo https://github.com/fanduel/cookies can solve this criminal omission

Oh this is awesome! If they would like to make a PR with the changes it will be happily accepted.

**Comment by xchwarze** [comment]
@YoliFD Could they do a PR with your work?
For the BC that it has it could be the new version 3.0.0

**Comment by Dan-Wood** [comment]
@xchwarze @YoliFD You can just PR it yourself back to master...

**Comment by YoliFD** [comment]
Hey folks, a little late to the party but I have made a PR that should address this as requested, as well as a bunch of other issues. Feel free to take a peek here https://github.com/react-native-community/cookies/pull/45 Any thoughts are welcome.

**Comment by xchwarze** [comment]
thanks for the amazing work!

**Comment by Dan-Wood** [comment]
Any idea when this will get merged and packages updated?

**Comment by safaiyeh** [comment]
Hi @Dan-Wood I'm currently testing out the branch! Hope fully we can get it in this week.

**Comment by niloufarMakhzani** [comment]
Any update on this issue?

**Comment by safaiyeh** [comment]
There’s an open PR for this! I’ll see if I can get it merged.

**Comment by TommyLeong** [comment]
> There’s an open PR for this! I’ll see if I can get it merged some more fixes need to be done. setFromResponse should handle what you need
I'm confused whether this merged solved `.set()` in Android? I have actually face crashed in Android today on One Plus 6T, Android OS 9. Does anyone else face this?

**Comment by safaiyeh** [comment]
Closing as set is supported. @TommyLeong could you create an issue with what you are experiencing
