### ISSUE TITLE
Simplify CookieManager.get() native implementations

### ISSUE THREAD

**Issue by safaiyeh** [react-native-community/cookies#29]
# Feature Request
Currently, the iOS and Android implementations fetch and iterate through the cookies. From @brentvatne, it is generally better to have implementations JS when possible.

## Why it is needed

• Better maintainability 

## Possible implementation
• Refactor iOS and Android `get()` to a list of the cookies
• Create a shared JS implementation to iterate and return the correct cookies to the app

**Comment by Aure77** [comment]
Native `get()` actually doesn't return the same structure between iOS & Android (that is a problem with typescript definition...). A refactor is welcome !

**Comment by YoliFD** [comment]
The return from the get method has now been aligned with PR #45
