### ISSUE TITLE
Invariant Violation: @react-native-community/cookies: Add RNCookieManagerIOS.h and RNCookieManagerIOS.m to your Xcode project

### ISSUE THREAD

**Issue by alexhancock** [react-native-community/cookies#31]
# Bug

I experience this whenever I try to use the library:

<img width="493" alt="Screen Shot 2020-02-10 at 5 35 09 PM" src="https://user-images.githubusercontent.com/427516/74205784-9c6f4a80-4c2d-11ea-9f31-f800127c04c4.png">

## Environment info

React native info output:

```bash
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.39 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.21.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

Library version: 2.0.3

## Steps To Reproduce

expo init debugapp

cd debugapp

yarn add @react-native-community/cookies

react-native link @react-native-community/cookies

Add “import CookieManager from '@react-native-community/cookies’;” to App.js

yarn start

(Click “Run on iOS Simulator” in the Expo UI)

Wait for the app to come up (you may need to reload it to see the error)

Describe what you expected to happen:

No error should appear after following initial setup instructions

## Reproducible sample code

https://github.com/alexhancock/react-native-cookies-debugissue

**Comment by SeanMcP** [comment]
@alexhancock I don't know how it works with Expo, but I had to add `@react-native-community/cookies` to the `Podfile` too:

```rb
pod 'react-native-cookies', :path => '../node_modules/@react-native-community/cookies/ios'
```

**Comment by safaiyeh** [comment]
This module currently does not support Expo. You can follow this issue: https://github.com/react-native-community/cookies/issues/17 for information/updates

**Comment by alexhancock** [comment]
@safaiyeh Thanks very much

**Comment by witacur** [comment]
Thanks @SeanMcP this help me out. 
I'm using `@react-native-community/cookies` at `4.0.1` the podspec file is now at ../node_modules/@react-native-community/cookies so 
`pod` 'react-native-cookies', :path => '../node_modules/@react-native-community/cookies'`
worked for me
