### ISSUE TITLE
CookieManager.get() returns an empty object when using WKWebView

### ISSUE THREAD

**Issue by timrwhi** [react-native-community/cookies#34]
# Bug

Using `CookieManager.get('https://mydomain.com', true)` returns an empty object. `CookieManager.getAll(true)` contains the cookies for `.mydomain.com`. Seems like the logic on this line might be backwards: https://github.com/react-native-community/cookies/blob/master/ios/RNCookieManagerIOS/RNCookieManagerIOS.m#L142

## Environment info

React native info output:

```bash
 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 98.53 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v10.15.1/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9
```

Library version: 2.0.3

## Steps To Reproduce

1. Use WKWebView
2. Have a cookie for https://mydomain.com
3. `CookieManager.get('https://mydomain.com', true).then(res => console.log(res)) // {}`
4. `CookieManager.getAll(true).then(res => console.log(res)) // {..., "the-cookie": {..., domain: ".mydomain.com"}, "another-cookie": {..., domain: ".other.com"}`
...

Describe what you expected to happen:

1. Use WKWebView
2. Have a cookie for https://mydomain.com
3. `CookieManager.get('https://mydomain.com', true).then(res => console.log(res)) // {..., "the-cookie": {..., domain: ".mydomain.com"}}`
4. `CookieManager.getAll(true).then(res => console.log(res)) // {..., "the-cookie": {..., domain: ".mydomain.com"}, "another-cookie": {..., domain: ".other.com"}`

**Comment by safaiyeh** [comment]
Thanks for the issue! I've notice this happen as well.

**Comment by Foskas** [comment]
Hi guys,

Do we have any update on this ? I'm facing issues with cookies in release mode for iOS.
The cookies are missing and I can't keep my session without them.

Thanks!
