### ISSUE TITLE
UIWebView question - Is it still used?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/cookies#35]
Hello,

With the removal/deprecation of `UIWebView`, I'm wondering if this library still uses it. The main concern is that if adding this library would result in warning messages from Apple due to references to `UIWebView`.  If it is no longer used, are the docs outdated? Is there even a purpose on having the `useWebKit` flags?

Thanks.

**Comment by safaiyeh** [comment]
`NSHTTPCookieStorage` is not deprecated. This is the default cookie store for cookies not related to a WebView. `useWebKit` is more about using the `WKWebView` related cookies as it has it is own store.

Is there a potential enhancement given this? @cristianoccazinsp

**Comment by cristianoccazinsp** [comment]
I might be a bit confused or not informed enough, but with webviews only usable with `WKWebView`, what would be the purpose of using UIWebView's cookies?

**Comment by safaiyeh** [comment]
`NSHTTPCookieStorage` can store cookies not from a WebViews. Just from normal http requests

**Comment by cristianoccazinsp** [comment]
Got it, so as long as there are no references to `UIWebView` in the code there should be nothing to worry about. My main concern is getting another library to trigger apple's deprecation warnings.

**Comment by safaiyeh** [comment]
Yup! This module should not trigger any deprecation warnings.
