### ISSUE TITLE
Add support for "set" cookies for Android.

### ISSUE THREAD

**Issue by alexyazvinsky** [react-native-community/cookies#44]
# Add support for "set" cookies for Android.

Add support for "set" cookies for Android.
Regarding to the latest changes:
https://github.com/facebook/react-native/commit/cc845ccfb4c0f841b876bca55c5f70efd72be538

**Comment by safaiyeh** [comment]
Thanks for the issue, we have an open one here tracking this: https://github.com/react-native-community/cookies/issues/25

If you'd like to pick it up, it would be appreciated :)
