### ISSUE TITLE
Can this set cookies in WebView?

### ISSUE THREAD

**Issue by nickmccomb** [react-native-community/cookies#50]
# Question

Does this set cookies for the WebView component?

For example:

1.  Login to www.abc.com via API
2. Save response token
3. Set response token as cookie with CookieManager.set
4. Go to www.abc.com in a WebView

Would i be authenticated because the cookie is set?

**Comment by DivyatejaChe** [comment]
Hey @nickmccomb is there a reason you closed it? I am trying to solve a similar problem - any guidance here?

**Comment by VadimZP** [comment]
@nickmccomb hello! Any reply from you?

**Comment by VadimZP** [comment]
@DivyatejaChe I did a research and I suppose that yes. `CookieManager.set` sets cookies in Webview's internal cookie store. On every subsequent request Webview will attach these cookies.
