### ISSUE TITLE
Exception '-[NSException localizedDescription]: unrecognized selector sent to instance 0x60000083bf00' was thrown while invoking set on target RNCookieManagerIOS

### ISSUE THREAD

**Issue by VickyStash** [react-native-community/cookies#56]
# Question

I have tried set() method from example and it gives me: "Exception '-[NSException localizedDescription]: unrecognized selector sent to instance 0x60000083bf00' was thrown while invoking set on target RNCookieManagerIOS"

For example:
```javascript
const newCookie = {
      name: 'myCookie',
      value: 'myValue',
      domain: 'some domain',
      path: '/',
      version: '1',
      expires: '2015-05-30T12:30:00.00-05:00',
    };
    const useWebKit = true;
    CookieManager.set('http://example.com', newCookie, useWebKit).then(
      (res) => {
        console.log('CookieManager.set from webkit-view =>', res);
      },
    );
```

![image](https://user-images.githubusercontent.com/23176449/84198827-cd14a300-aaac-11ea-9cdf-12620dc97cf6.png)

I am using iOS ver 13.0.
In package.json:
"@react-native-community/cookies": "^3.0.0",
"react-native": "^0.62.2",

**Comment by focux** [comment]
How did you fix this? I'm also having this issue.

**Comment by VickyStash** [comment]
@focux I used it in a wrong way cause documentation wasn't clear for me
Try to do it this way and it'll work, a cookie with name 'test' and value 'test' will be created

```
const newCookie = {
      name: 'test',
      value: 'test',
    };
    const useWebKit = true;
    CookieManager.set('http://example.com', newCookie, useWebKit).then(
      (res) => {
        console.log('CookieManager.set from webkit-view =>', res);
      },
    );
```

**Comment by oferRounds** [comment]
@VickyStash not sure – what is the difference from the original way you tried? Not sure I understand what was the issue

**Comment by oferRounds** [comment]
Getting the same problem

**Comment by safaiyeh** [comment]
@oferRounds Check out this issue https://github.com/react-native-community/cookies/issues/59 let me know if the discussion there is similar to what you are experiencing
