### ISSUE TITLE
SetFromResponse doesn't seem useful with no access to response headers

### ISSUE THREAD

**Issue by jpodpro** [react-native-community/cookies#77]
# Question

hi there - i'm confused about how to use `SetFromResponse` since you can't actually read the setcookie header value from a fetch request. 

in my app i have performed a fetch request that responds with a setcookie header. this header should be saved for use in react-native-webview but it's not working (not on ios). so i'm here trying to manually set the cookie. however i have no access to it so i'm pretty confused as to how this is supposed to work.

the flow of using fetch and then loading the webview works perfectly fine on android - that is to say the cookie is set via fetch request and then is available when the webview reloads. i have also enabled the webview shared cookies setting.

**Comment by pascaljung** [comment]
Hey, we use [axios](https://www.npmjs.com/package/axios) in our app to do the backend request that returns the cookies. In axios, it's possible to read the `set-cookies` header. Maybe that helps :)

**Comment by jpodpro** [comment]
thanks - using an alternative to fetch seems to be the most reasonable solution.
